/**
 * Pins what the audit chain actually guarantees against what the shipped docs say about it.
 *
 * THE DEFECT. Two security documents asserted cryptographic signing that does not happen:
 *
 *   docs/security/SECURITY.md   "All high-tier (T1-T3) agent actions are cryptographically
 *                                signed using Ed25519."
 *   docs/security/SECURITY.md   "The AUDIT.jsonl log is finalized with Merkle-root integrity
 *                                manifests to prevent tampering."
 *   docs/security/ZTAI-OVERVIEW.md  "every agent action is cryptographically signed and
 *                                    non-repudiable", per-persona Ed25519 keypairs, a DID per
 *                                    agent, a Merkle-root every 50 entries.
 *
 * Measured against a live 3116-entry .planning/AUDIT.jsonl: ZERO entries carry a `signature` or
 * `did` field. The entry schema is exactly event, target_id, description, agent, id, timestamp,
 * previous_hash, _hash. `.planning/audit-archive/` contains only `.gitkeep`. `ENABLE_ZTAI` has no
 * readers anywhere in bin/. bin/governance/ztai-archiver.js has no caller outside tests.
 *
 * NUANCE THAT MATTERS, and which "the feature does not exist" got wrong: the Ed25519 code IS real.
 * bin/governance/ztai-manager.js:34,74 genuinely calls crypto.generateKeyPair('ed25519'). The
 * capability is implemented and never invoked. And the archiver's field is misnamed at the code
 * level too — ztai-archiver.js:57 sets `merkleRoot: cumulativeHash`, a LINEAR chain hash. There is
 * no hash tree and no inclusion proof, so "Merkle" was the wrong word throughout.
 *
 * WHAT IS GENUINELY GOOD, and worth not overcorrecting away: the hash chain works and is
 * independently verifiable. Measured on a 60-entry chain written by the real appendAuditEntrySync
 * and checked by the real bin/verify-audit.js:
 *
 *     intact                 -> "audit chain valid: 60 entries", exit 0     <- the control
 *     mutate a middle entry  -> "BROKEN at entry 30: hash mismatch (entry mutated)", exit 1
 *     delete a middle entry  -> "BROKEN at entry 30: previous_hash mismatch", exit 1
 *     truncate 20 from tail  -> "audit chain valid: 40 entries", EXIT 0     <- the one gap
 *     replay identical rows  -> not detected (content and ordering only)
 *
 * The truncation gap is inherent: each entry commits to its predecessor, so any prefix of a valid
 * chain is itself a valid chain. Closing it needs a commitment to LENGTH. So the accurate claim is
 * "detects mutation and mid-file deletion", not "immutable" or "non-repudiable".
 *
 * These tests are BIDIRECTIONAL. If signing or a length commitment ever lands, the assertions here
 * fail and tell you to update the docs — rather than freezing today's limitations into a permanent
 * requirement.
 */
'use strict';

const assert = require('node:assert');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { spawnSync } = require('node:child_process');

const REPO_ROOT = fs.realpathSync(path.join(__dirname, '..'));
const VERIFY = path.join(REPO_ROOT, 'bin', 'verify-audit.js');
const { appendAuditEntrySync } = require(path.join(REPO_ROOT, 'bin', 'autonomous', 'audit-writer.js'));
// Corroboration only — NEVER a precondition. See the note on hermeticity below.
const LIVE_AUDIT = path.join(REPO_ROOT, '.planning', 'AUDIT.jsonl');
const SEC_ROOT = path.join(REPO_ROOT, 'SECURITY.md');
const SEC_DOCS = path.join(REPO_ROOT, 'docs', 'security', 'SECURITY.md');
const ZTAI = path.join(REPO_ROOT, 'docs', 'security', 'ZTAI-OVERVIEW.md');

let passed = 0;
let failed = 0;
const tests = [];
function test(name, fn) { tests.push({ name, fn }); }

/**
 * HERMETIC BY CONSTRUCTION — and it was not, which broke CI.
 *
 * The first version read a 200-entry prefix of the repo's own `.planning/AUDIT.jsonl`. That file is
 * GITIGNORED and untracked, so it exists on a maintainer's machine and never in CI. The suite passed
 * locally and failed on the runner with four assertions ENOENT:
 *
 *     ✗ FAIL  audit-claims-honesty.test.js
 *              ❌ no audit entry carries a signature or DID
 *                 the live audit log must exist for this measurement
 *              ❌ mutating a middle entry IS detected
 *                 ENOENT: ... open '/home/runner/work/MindForge/MindForge/.planning/AUDIT.jsonl'
 *
 * A test that depends on an untracked artifact is worse than no test: it reports green to the person
 * who can least act on it and red to everyone else. Same defect class as the rest of this audit —
 * an instrument whose result is decided by its environment rather than by the code under test.
 *
 * The chain is now GENERATED by the real writer, `appendAuditEntrySync`, which shares
 * bin/governance/audit-hash.js with the verifier. So this is not a weaker substitute for the live
 * log — it exercises the same two code paths against data whose provenance is known, and it no
 * longer silently measures whatever happens to be sitting in one developer's working tree.
 *
 * @param {(lines: string[]) => string[]} mutate  transform applied to the generated chain
 * @param {number} [n]  entries to generate
 */
function verifyChain(mutate, n = 60) {
  const dir = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), 'mf-auditclaim-')));
  const auditPath = path.join(dir, '.planning', 'AUDIT.jsonl');
  try {
    for (let i = 0; i < n; i++) {
      appendAuditEntrySync(auditPath, {
        event: `probe_${i}`,
        target_id: `T-${i}`,
        description: `synthetic entry ${i}`,
        agent: 'audit-claims-honesty',
      });
    }
    const lines = fs.readFileSync(auditPath, 'utf8').split('\n').filter(Boolean);
    assert.strictEqual(lines.length, n, `the writer must have produced ${n} entries, got ${lines.length}`);
    fs.writeFileSync(auditPath, `${mutate(lines).join('\n')}\n`);
    // Pass the path explicitly (verify-audit.js takes argv[2]) rather than relying on cwd, so the
    // measurement cannot accidentally read the repo's own log.
    const r = spawnSync(process.execPath, [VERIFY, auditPath], { cwd: dir, encoding: 'utf8' });
    return { status: r.status, out: `${r.stdout || ''}${r.stderr || ''}`, lines };
  } finally { fs.rmSync(dir, { recursive: true, force: true }); }
}

/** Generate a chain with the real writer and hand back its parsed entries. */
function writtenEntries(n = 25) {
  const dir = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), 'mf-auditwrite-')));
  const auditPath = path.join(dir, '.planning', 'AUDIT.jsonl');
  try {
    for (let i = 0; i < n; i++) {
      appendAuditEntrySync(auditPath, {
        event: 'tier3_action', target_id: `T-${i}`, description: 'high-tier action', agent: 'probe',
      });
    }
    return fs.readFileSync(auditPath, 'utf8').split('\n').filter(Boolean).map((l) => JSON.parse(l));
  } finally { fs.rmSync(dir, { recursive: true, force: true }); }
}

// ── the live chain carries no signatures ─────────────────────────────────────

test('the WRITER does not sign — no entry it produces carries a signature or DID', () => {
  // Driven through the real appendAuditEntrySync rather than read off disk, so this holds on a fresh
  // clone and in CI. It also tests the stronger proposition: not "today's log happens to be unsigned"
  // but "the only thing that writes the log cannot produce a signature".
  const entries = writtenEntries(25);
  const signed = entries.filter((e) => 'signature' in e || 'did' in e);
  assert.strictEqual(signed.length, 0,
    `${signed.length} of ${entries.length} written entries carry a signature or did field. If signing `
    + 'has landed, that is GOOD — update docs/security/SECURITY.md and ZTAI-OVERVIEW.md, which '
    + 'currently say it is designed but not active, and then invert this assertion.');

  // The schema is exactly what the docs should describe, and nothing more.
  const keys = Object.keys(entries[0]).sort();
  assert.deepStrictEqual(keys,
    ['_hash', 'agent', 'description', 'event', 'id', 'previous_hash', 'target_id', 'timestamp'],
    `the entry schema changed to [${keys.join(', ')}]. If a cryptographic field appeared, the security `
    + 'docs need updating; if one vanished, the chain may have weakened.');

  // CORROBORATION, not a precondition, and deliberately NOT its own test. As a separate test the
  // absent-log branch would have to pass with no assertion — a test that cannot fail, which is the
  // exact smell this audit exists to remove. Folded in here, every test in this file always asserts
  // something real, and the live log adds evidence when a developer happens to have one.
  if (fs.existsSync(LIVE_AUDIT)) {
    const live = fs.readFileSync(LIVE_AUDIT, 'utf8').split('\n').filter(Boolean);
    const liveSigned = live.filter((l) => /"(signature|did)"\s*:/.test(l));
    assert.strictEqual(liveSigned.length, 0,
      `${liveSigned.length} of ${live.length} entries in the live log carry a signature or did field, `
      + 'while the writer provably cannot produce one. Something other than appendAuditEntrySync is '
      + 'writing that log.');
  }
});

test('this suite never GATES on the untracked live log', () => {
  // The regression guard for the CI break itself. .planning/AUDIT.jsonl is gitignored, so any
  // assertion whose success depends on its presence passes for the maintainer and fails for everyone
  // else. LIVE_AUDIT may therefore be read only behind an existsSync guard, and never asserted to
  // exist.
  // SCOPED TO EXCLUDE THIS TEST'S OWN BODY. A first version scanned the whole file and reported
  // "LIVE_AUDIT is referenced 8 times" — because the assertions below mention the token themselves.
  // A scanner counting its own source is the same self-referential defect that made an earlier check
  // in this very file pass on a See-also line it had written itself. The marker split is a literal
  // the scanner cannot match by accident.
  const self = fs.readFileSync(__filename, 'utf8');
  const SELF_MARKER = `test('this suite never ${'GATES'} on the untracked live log'`;
  const upToHere = self.slice(0, self.indexOf(SELF_MARKER));
  assert.ok(upToHere.length > 0, 'the self-exclusion marker must be found, or this check scans nothing');
  const code = upToHere.split('\n').filter((l) => !/^\s*(\/\/|\*|\/\*)/.test(l)).join('\n');
  assert.ok(!/assert[^\n]*existsSync\(LIVE_AUDIT\)/.test(code),
    'LIVE_AUDIT must never be asserted to exist — that is precisely what failed in CI with '
    + '"the live audit log must exist for this measurement"');
  const uses = (code.match(/LIVE_AUDIT/g) || []).length;
  assert.ok(uses <= 3,
    `LIVE_AUDIT is referenced ${uses} times; it should appear only in its declaration and inside one `
    + 'existsSync-guarded corroboration block. More references means the dependency is creeping back.');
  assert.match(code, /if \(fs\.existsSync\(LIVE_AUDIT\)\)/,
    'the only read of the live log must sit behind an existsSync guard');
});

test('ENABLE_ZTAI still has no readers in bin/', () => {
  // The switch the ZTAI docs imply exists. If it gains a reader the feature may be becoming real,
  // and the status banner must stop saying otherwise.
  const r = spawnSync('git', ['grep', '-l', 'ENABLE_ZTAI', '--', 'bin/'], { cwd: REPO_ROOT, encoding: 'utf8' });
  const files = (r.stdout || '').split('\n').filter(Boolean);
  assert.deepStrictEqual(files, [],
    `ENABLE_ZTAI is now read by: ${files.join(', ')}. Re-check whether the ZTAI status banner is ` +
    'still accurate.');
});

// ── what the chain does and does not detect ──────────────────────────────────

test('mutating a middle entry IS detected', () => {
  const r = verifyChain((l) => l.map((line, i) => (i === 30 ? line.replace('"event":"', '"event":"X_') : line)));
  assert.strictEqual(r.status, 1, `a mutated entry must break the chain. Output: ${r.out.slice(0, 200)}`);
  assert.match(r.out, /hash mismatch|entry mutated/i);
});

test('deleting a middle entry IS detected', () => {
  const r = verifyChain((l) => l.filter((_, i) => i !== 30));
  assert.strictEqual(r.status, 1, `a deleted middle entry must break the chain. Output: ${r.out.slice(0, 200)}`);
  assert.match(r.out, /previous_hash mismatch/i);
});

test('truncating the TAIL is NOT detected — and SECURITY.md says so', () => {
  // The one real gap, and the assertion that keeps the doc honest about it. Bidirectional: if a
  // length commitment lands and truncation starts failing verification, this test fails and asks for
  // the doc to be updated rather than silently keeping a stale limitation on the page.
  const intact = verifyChain((l) => l);
  assert.strictEqual(intact.status, 0,
    `the generated chain must verify clean first, or the control proves nothing. Got: ${intact.out.slice(0, 200)}`);

  const truncated = verifyChain((l) => l.slice(0, 40));
  const doc = fs.readFileSync(SEC_ROOT, 'utf8');

  if (truncated.status === 0) {
    assert.match(truncated.out, /valid: 40 entries/,
      `truncation went undetected but the message was unexpected: ${truncated.out.slice(0, 200)}`);
    assert.match(doc, /[Tt]runcat/,
      'tail truncation is undetected, so SECURITY.md MUST document it. A chain described as ' +
      '"tamper-evident" without naming this gap overstates the guarantee.');
    assert.ok(!/\bimmutable\b/i.test(doc) || /not\s+"?immutable/i.test(doc),
      'SECURITY.md must not call the chain "immutable" while a prefix of it verifies clean');
  } else {
    assert.fail(
      'tail truncation is now DETECTED — a length commitment must have landed. That is a real ' +
      'improvement: update the table in SECURITY.md and invert this branch.');
  }
});

// ── the docs no longer assert what does not happen ───────────────────────────

test('the security docs do not claim active signing', () => {
  // SCOPED TO THE CLAIM'S OWN BULLET, not the whole file.
  //
  // The first version checked "does this file contain a qualifier anywhere?" and was satisfied by a
  // sentence I had written myself in the See-also line — "most of it is design, not shipped
  // behaviour" — which is about a DIFFERENT document and qualifies nothing. Restoring both
  // unqualified signing claims left the test green: a document satisfying its own grep via unrelated
  // prose. That is the same defect this whole audit exists to find, produced by the audit's own test.
  //
  // A claim and its caveat have to be in the same breath to be read together, so the assertion now
  // requires them in the same bullet block.
  const bulletsOf = (text) => {
    const out = [];
    let cur = null;
    for (const line of text.split('\n')) {
      if (/^\s*[-*]\s/.test(line)) { if (cur) out.push(cur); cur = line; }
      else if (cur !== null && /^\s+\S/.test(line)) { cur += `\n${line}`; }
      else { if (cur) out.push(cur); cur = null; }
    }
    if (cur) out.push(cur);
    return out;
  };
  const QUALIFIER = /NOT ACTIVE|NOT SHIPPED|DESIGN DOCUMENT|DESIGNED, NOT|not implemented/i;
  const CLAIM = /cryptographically signed|non-repudiab/i;

  for (const [label, file] of [['docs/security/SECURITY.md', SEC_DOCS], ['ZTAI-OVERVIEW.md', ZTAI]]) {
    const text = fs.readFileSync(file, 'utf8');
    const offenders = bulletsOf(text)
      .filter((b) => CLAIM.test(b) && !QUALIFIER.test(b))
      .map((b) => b.trim().split('\n')[0].slice(0, 100));
    assert.deepStrictEqual(offenders, [],
      `${label} has ${offenders.length} bullet(s) asserting signing or non-repudiation with no ` +
      'qualifier in the same bullet, while 0 of the live chain\'s entries are signed:\n  ' +
      `${offenders.join('\n  ')}`);
  }
});

test('the qualifier check is scoped to the bullet, not the file', () => {
  // Non-vacuity guard for the test above. Feeds it a document whose ONLY qualifier sits in an
  // unrelated bullet — exactly the shape that fooled the first version — and requires it to be
  // rejected. Without this, a future refactor could silently widen the scope back to file-level.
  const bulletsOf = (text) => text.split('\n').filter((l) => /^\s*[-*]\s/.test(l));
  const QUALIFIER = /NOT ACTIVE|NOT SHIPPED|DESIGN DOCUMENT|DESIGNED, NOT|not implemented/i;
  const CLAIM = /cryptographically signed|non-repudiab/i;
  const decoy = [
    '- **Asymmetric Signing**: all actions are cryptographically signed using Ed25519.',
    '- **See also:** the overview is design, NOT SHIPPED behaviour.',
  ].join('\n');
  const offenders = bulletsOf(decoy).filter((b) => CLAIM.test(b) && !QUALIFIER.test(b));
  assert.strictEqual(offenders.length, 1,
    'a signing claim must be flagged even when an unrelated bullet carries a qualifier — the ' +
    'file-scoped version of this check missed exactly this case');
});

test('ZTAI-OVERVIEW.md leads with a status banner', () => {
  const head = fs.readFileSync(ZTAI, 'utf8').split('\n').slice(0, 12).join('\n');
  assert.match(head, /STATUS: DESIGN DOCUMENT/i,
    'the banner must be at the top — a caveat further down is read after the claims it qualifies');
});

test('this chain is not called a Merkle tree in the core security docs', () => {
  // ztai-archiver.js:57 sets `merkleRoot: cumulativeHash` — a linear chain hash. There is no hash
  // tree and no inclusion proof, so the word misdescribes the guarantee. Scoped to the two documents
  // a security reviewer reads first; the term survives in changelogs and dated release notes, which
  // are historical records and should not be rewritten.
  for (const [label, file] of [['SECURITY.md', SEC_ROOT], ['docs/security/SECURITY.md', SEC_DOCS]]) {
    const text = fs.readFileSync(file, 'utf8');
    const bad = text.split('\n').filter((l) => /merkle/i.test(l) && !/not a Merkle|misnamed|wrong word|linear/i.test(l));
    assert.deepStrictEqual(bad, [],
      `${label} still describes the chain as Merkle without correcting it:\n  ${bad.join('\n  ')}`);
  }
});

// ── the repo-wide "Merkle" sweep (HON-merkle-sweep) ──────────────────────────
//
// The test above covers the two documents a security reviewer opens first. It left 31 OTHER tracked
// files calling the linear chain "Merkle-linked" — including `.claude/CLAUDE.md`, its `.agent/` twin
// and the generated `mindforge-protocol` skill, all THREE copies of seven `/mindforge:*` command
// docs, `.mindforge/skills/orch-pipeline/SKILL.md`, `CODEBASE-MAP.md` and
// `MINDFORGE-AGENTIC-SECURITY.md`. Those are what an agent reads as a current statement of
// behaviour, so they mattered more than the security pages did.
//
// Re-measured on the tree these assertions were written against (base 963902d): `git grep -Il -i
// merkle` matched 49 tracked files before the sweep and 18 after. Detection profile, measured
// through the real writer and the real bin/verify-audit.js (see verifyChain above): mutation ->
// exit 1, mid-file deletion -> exit 1, TAIL TRUNCATION -> exit 0. So "Merkle", "tamper-proof" and
// "immutable" all overstate it.

/** A line mentions the term at all. */
const MERKLE_MENTION = /merkle/i;

/**
 * A line that mentions the term but CORRECTS it. Deliberately STRONGER than the regex in the
 * per-document test above, which also accepts a bare `linear`: the sentence "a Merkle tree verifies
 * in linear time" satisfies that, so it is a marker a false claim can meet by accident. Pinned by
 * the decoy assertions below.
 */
const MERKLE_CORRECTED = /not a Merkle|not a hash tree|no hash tree|no inclusion proof|misnamed|wrong word/i;

/**
 * Paths where the term is allowed to survive. A trailing `/` is a directory prefix; everything else
 * is an exact repo-relative path. Every entry is justified, and `the Merkle allowlist excludes only
 * what it names` below asserts that each one really does cover a file that mentions the term AND
 * that none of them shadows a live instructional path.
 */
const MERKLE_ALLOWLIST = [
  // HISTORICAL RECORD — a record of what was said at the time. Rewriting a changelog or a dated
  // release note destroys the history that makes the correction legible.
  'RELEASENOTES.md',
  'changelogs/',
  'docs/research/',       // dated audit research reports (2026-08-*) that FOUND this defect
  'docs/superpowers/',    // dated plans/specs (2026-05-30-*) recording a past decision
  // CODE IDENTIFIER, reported rather than swept. ztai-archiver.js:57 persists `merkleRoot` into
  // .mindforge/audit/manifests/*.json and verifyIntegrity():157 reads that key back, so a rename
  // invalidates every manifest already on disk. It needs a migration, not a doc sweep.
  'bin/governance/ztai-archiver.js',
  // GENERATED SNAPSHOT — an LLM-written code index rewritten wholesale by its own tool. Hand-edits
  // are overwritten on the next run and nobody reads it as instruction.
  '.understand-anything/knowledge-graph.json',
  // THIS GATE'S OWN EVIDENCE. These files quote the false claims in order to forbid them, and
  // reference the `merkleRoot` identifier; a scanner that reads its own decoys reports itself.
  'tests/audit-claims-honesty.test.js',
  'tests/ztai-archiver-integrity.test.js',
  'tests/ztai-enterprise.test.js',
];

/**
 * The live files still ALLOWED to mention the term, because each mention is a correction. Pinned
 * exactly: if the allowlist ever widens, this set shrinks and the assertion fails rather than the
 * gate quietly covering less.
 */
const MERKLE_LIVE_WITH_CORRECTIONS = [
  'SECURITY.md',
  'docs/architecture/V4-SWARM-MESH.md',
  'docs/security/SECURITY.md',
  'docs/security/ZTAI-OVERVIEW.md',
];

/**
 * Live instructional paths the allowlist must NEVER cover. Half are files this sweep corrected, the
 * rest are the obvious places a reintroduction would land. Each is asserted TRACKED, because
 * `isAllowlisted('typo.md') === false` would otherwise satisfy the check for free.
 */
const MERKLE_MUST_BE_SCANNED = [
  '.claude/CLAUDE.md', '.agent/CLAUDE.md', 'plugins/mindforge/skills/mindforge-protocol/SKILL.md',
  '.claude/commands/mindforge/orch-fix-defect.md', '.agent/mindforge/orch-fix-defect.md',
  'plugins/mindforge/commands/orch-fix-defect.md',
  '.mindforge/skills/orch-pipeline/SKILL.md', '.mindforge/skills/agent-architecture-audit/SKILL.md',
  '.mindforge/production/production-checklist.md',
  'CODEBASE-MAP.md', 'MINDFORGE-AGENTIC-SECURITY.md', 'README.md', 'MINDFORGE.md', 'AGENTS.md',
  'bin/harness-audit.js', 'bin/engine/sre-manager.js',
  'SECURITY.md', 'docs/security/SECURITY.md', 'docs/security/ZTAI-OVERVIEW.md',
  'docs/architecture/V4-SWARM-MESH.md',
];

const isMerkleAllowlisted = (f) =>
  MERKLE_ALLOWLIST.some((a) => (a.endsWith('/') ? f.startsWith(a) : f === a));

/**
 * The gate's predicate, taking its input as an argument so the decoy assertions below exercise the
 * SAME code the repo scan does rather than a re-implementation of it.
 * @param {Array<{file: string, line: number, text: string}>} hits
 */
const merkleOffenders = (hits) => hits.filter(
  (h) => !isMerkleAllowlisted(h.file) && MERKLE_MENTION.test(h.text) && !MERKLE_CORRECTED.test(h.text));

/** Tracked files containing the term, via git so the result is identical on a fresh clone. */
function merkleFiles() {
  const r = spawnSync('git', ['grep', '-Il', '-i', 'merkle', '--', '.'], { cwd: REPO_ROOT, encoding: 'utf8' });
  // git grep exits 0 with matches, 1 with none, >1 on error. Folding an error into "no matches" is
  // precisely how a gate reports success while measuring nothing.
  assert.ok(r.status === 0 || r.status === 1,
    `git grep failed with status ${r.status}, so this gate measured nothing: ${r.stderr}`);
  return (r.stdout || '').split('\n').filter(Boolean).sort();
}

/** @param {string[]} files @returns {Array<{file: string, line: number, text: string}>} */
function merkleHits(files) {
  const out = [];
  for (const f of files) {
    const lines = fs.readFileSync(path.join(REPO_ROOT, f), 'utf8').split('\n');
    lines.forEach((text, i) => { if (MERKLE_MENTION.test(text)) out.push({ file: f, line: i + 1, text }); });
  }
  return out;
}

test('no live instructional file calls the audit chain a Merkle anything', () => {
  const files = merkleFiles();
  // Non-vacuity floor. 18 tracked files matched when this was written; a git grep that suddenly
  // matches almost nothing means the scan broke, not that the repo got clean.
  assert.ok(files.length >= 10,
    `only ${files.length} tracked file(s) matched /merkle/i (18 when written) — the scan is broken, `
    + 'not the repo clean');

  const live = files.filter((f) => !isMerkleAllowlisted(f));

  // The offending LINES first, because that is the actionable message. Asserting the file SET first
  // reported "classify the new one" for a plain reintroduction into a file already on the list —
  // true but unhelpful.
  const bad = merkleOffenders(merkleHits(live)).map((h) => `${h.file}:${h.line}: ${h.text.trim().slice(0, 120)}`);
  assert.deepStrictEqual(bad, [],
    `${bad.length} line(s) describe the audit chain as Merkle without correcting it. It is a LINEAR `
    + 'SHA-256 back-link chain (bin/governance/audit-hash.js): no hash tree, no inclusion proof. Say '
    + `"hash-chained append-only audit log (SHA-256 back-links)" instead:\n  ${bad.join('\n  ')}`);

  // Then the SET, pinned exactly: a widened allowlist shrinks this list, and a new file that merely
  // mentions the term correctively still has to be classified on purpose rather than drift in.
  assert.deepStrictEqual(live, MERKLE_LIVE_WITH_CORRECTIONS,
    'the set of live files mentioning the term changed. Classify it: LIVE INSTRUCTIONAL '
    + '(correct it), HISTORICAL RECORD (add to MERKLE_ALLOWLIST with a reason), or CODE IDENTIFIER '
    + `(decide deliberately). Got:\n  ${live.join('\n  ')}`);
});

test('the Merkle gate catches a reintroduction, in both directions', () => {
  // NON-VACUITY for the test above, through the same predicate. Without this pair, MERKLE_MENTION
  // could stop matching, or MERKLE_CORRECTED could start matching everything, and the repo scan
  // would still report zero offenders.
  const claim = '- [ ] **Audit Always**: all entries must be Merkle-linked.';

  assert.strictEqual(merkleOffenders([{ file: '.claude/CLAUDE.md', line: 81, text: claim }]).length, 1,
    'the exact sentence this sweep removed from .claude/CLAUDE.md:81 must be flagged if it returns');
  assert.strictEqual(merkleOffenders([{ file: 'changelogs/v10.0.0.md', line: 11, text: claim }]).length, 0,
    'the allowlist must be decided by PATH — the identical sentence is legitimate history in a changelog');
  assert.strictEqual(
    merkleOffenders([{ file: 'SECURITY.md', line: 70, text: 'Not a Merkle tree: no inclusion proof.' }]).length, 0,
    'a mention that corrects itself must pass, or the gate forces the correction off the page');
  assert.strictEqual(
    merkleOffenders([{ file: 'SECURITY.md', line: 1, text: 'A Merkle tree verifies in linear time.' }]).length, 1,
    'a bare "linear" must NOT count as a correction marker — that is how a false claim satisfies its '
    + 'own guard by accident');
});

test('the Merkle allowlist excludes only what it names', () => {
  const files = merkleFiles();

  // (a) No dead or speculative entries: each must actually cover a file that mentions the term. An
  // allowlist entry with nothing behind it is silent scope removal waiting for a future mention.
  const unjustified = MERKLE_ALLOWLIST.filter(
    (a) => !files.some((f) => (a.endsWith('/') ? f.startsWith(a) : f === a)));
  assert.deepStrictEqual(unjustified, [],
    `${unjustified.length} allowlist entry(ies) cover no file that mentions the term, so they only `
    + `widen the exemption: ${unjustified.join(', ')}`);

  // (b) The allowlist does not swallow the live surface. "This sweep touches many files; a gate that
  // excludes too much is indistinguishable from one that works."
  const trackedProbe = spawnSync('git', ['ls-files', '--', ...MERKLE_MUST_BE_SCANNED],
    { cwd: REPO_ROOT, encoding: 'utf8' });
  assert.strictEqual(trackedProbe.status, 0, `git ls-files failed: ${trackedProbe.stderr}`);
  const tracked = new Set((trackedProbe.stdout || '').split('\n').filter(Boolean));
  const missing = MERKLE_MUST_BE_SCANNED.filter((p) => !tracked.has(p));
  assert.deepStrictEqual(missing, [],
    `${missing.length} pinned path(s) are not tracked, so asserting they are un-allowlisted proves `
    + `nothing — fix the path or drop it: ${missing.join(', ')}`);

  const shadowed = MERKLE_MUST_BE_SCANNED.filter((p) => isMerkleAllowlisted(p));
  assert.deepStrictEqual(shadowed, [],
    `${shadowed.length} live instructional path(s) are exempted by the allowlist, so a reintroduction `
    + `there would go unnoticed: ${shadowed.join(', ')}`);
});

test('no published security doc leaks a local filesystem path', () => {
  // docs/security/SECURITY.md shipped a `file:///Users/sairamugge/Desktop/MindForge/...` link, which
  // both leaked the maintainer's directory layout and pointed at a path that no longer exists.
  for (const [label, file] of [['SECURITY.md', SEC_ROOT], ['docs/security/SECURITY.md', SEC_DOCS], ['ZTAI-OVERVIEW.md', ZTAI]]) {
    const text = fs.readFileSync(file, 'utf8');
    assert.ok(!/file:\/\/\//.test(text), `${label} contains a file:/// URL`);
    assert.ok(!/\/Users\/[a-z]/i.test(text), `${label} contains an absolute /Users/ path`);
  }
});

(async () => {
  for (const { name, fn } of tests) {
    try { await fn(); console.log(`  ✅  ${name}`); passed++; }
    catch (e) { console.error(`  ❌  ${name}\n      ${e.message}`); failed++; }
  }
  console.log(`\nAudit Claims Honesty: ${passed} passed, ${failed} failed`);
  if (failed > 0) process.exit(1);
})();
